### PR TITLE
Thermo cleanup

### PR DESCRIPTION
**Pull request by chadagreene**
Tidying up thermo.m a little bit and creating some test data for further developments.

### CODE REVIEW

**Comment by asinghvi17** [comment]
@chadagreene #30 added CI so you may want to merge master in or rebase

**Comment by alex-s-gardner** [comment]
@chadagreene @asinghvi17 is saying that your PR is not using the latest version of main... can you update your brach that you are wanting to merge before this PR is accepted?

**Comment by chadagreene** [comment]
Yep, can do, but it'll take a few days.

**Comment by NJSchlegel** [comment]
I don't think this PR has any conflicts with the main brach and the introduction of CI.  None of the updates done should have changed any of the answers for the test I don't think.

**Comment by asinghvi17** [comment]
It wouldn't conflict (ideally :D), but merging `main` in here would allow CI to run on this branch as well.

**Comment by NJSchlegel** [comment]
@chadagreene , the merge should be instantaneous. What would be great is to add your new thermo test to the CI, testscript.m , so it benchmarks for future contributions.

**Pull request closed without merging**
