### PR TITLE
Update accumulation.m

### PR DESCRIPTION
**Pull request by chadagreene**
Removing unused mass values.

### CODE REVIEW

**Comment by alex-s-gardner** [comment]
@chadagreene is this PR ready for review or is it a WIP?

**Comment by chadagreene** [comment]
Ready for review.. Is there a way I should denote that?

**Comment by alex-s-gardner** [comment]
You can request review but probably better to assume all PR's are ready to merge unless indicated otherwise ... 

Just an FYI a PR can contain multiple commits to a branch

**Review by alex-s-gardner — APPROVED** [review]
Changes look safe

**Pull request merged**
